---
title: "tm_beach"
format: html
editor: visual
---

## Tidy Modeling with R

Playground for source code from <https://www.tmwr.org/>

## Chicago

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
# install.packages("tidyverse")
#install.packages("lubridate")

library(tidyverse)
library(lubridate)
```

You can add options to executable code like this

```{r}
url <- "https://data.cityofchicago.org/api/views/5neh-572f/rows.csv?accessType=DOWNLOAD&bom=true&format=true"

all_stations <- 
  # Step 1: Read in the data.
  read_csv(url) %>% 
  # Step 2: filter columns and rename stationname
  dplyr::select(station = stationname, date, rides) %>% 
  # Step 3: Convert the character date field to a date encoding.
  # Also, put the data in units of 1K rides
  mutate(date = mdy(date), rides = rides / 1000) %>% 
  # Step 4: Summarize the multiple records using the maximum.
  group_by(date, station) %>% 
  summarize(rides = max(rides), .groups = "drop")
```

The `echo: false` option disables the printing of code (only output is displayed).

```{r}
# View(all_stations)

write.csv(df,file='/Users/admin/new_file.csv', row.names=FALSE)
```
